controller_manager:
  ros__parameters:
    update_rate: 30

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_footprint

    left_wheel_names: ['lftw']
    right_wheel_names: ['rgtw']
    wheel_separation: 0.133
    wheel_radius: 0.017

    use_stamped_vel: false